---
- block:
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest
      update_cache: yes

  - name: install epel-release
    yum:
      name: epel-release
      state: latest
      update_cache: yes

  - name: install nginx
    yum:
      name: nginx
      state: latest
      update_cache: yes
  
  - name: instanciate proxy templates
    template:
        dest: /etc/nginx/conf.d/proxy.conf
        src: proxy.conf.j2
  
  - name: start nginx
    service:
        name: nginx
        state: started
  become: yes


